-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW product_sales (product_id, product_name, category_name, total_sold, total_revenue) AS SELECT p.product_id, p.product_name, cat.category_name,
               SUM(oi.quantity) as total_sold,
               SUM(oi.quantity * oi.unit_price) as total_revenue
        FROM products p
        LEFT JOIN order_items oi ON p.product_id = oi.product_id
        LEFT JOIN categories cat ON p.category_id = cat.category_id
        GROUP BY p.product_id, p.product_name, cat.category_name;

