version: '3.8'
services:
  db:
    image: postgres:17.6
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.29.1
    container_name: ecommerce-nginx
    ports:
      - "8088:80"
    depends_on:
      - payara
      - payara2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  payara:
    build: .
    container_name: ecommerce-payara
    hostname: payara
    environment:
      DB_HOST: db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      JVM_ARGS: "-Djdk.util.zip.disableZip64ExtraFieldValidation=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9009"
    command: ["--deploydir", "/opt/payara/deployments", "--clustermode", "dns:payara:6900,payara2:6900"]
    ports:
      - "8080:8080"
      - "9009:9009"
    volumes:
      - ./deploy:/opt/payara/deployments
    depends_on:
      - db

  payara2:
    build: .
    container_name: ecommerce-payara-2
    hostname: payara2
    environment:
      DB_HOST: db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      JVM_ARGS: "-Djdk.util.zip.disableZip64ExtraFieldValidation=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9009"
    command: ["--deploydir", "/opt/payara/deployments", "--clustermode", "dns:payara:6900,payara2:6900"]
    ports:
      - "8081:8080"
      - "9010:9009"
    volumes:
      - ./deploy:/opt/payara/deployments
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:9.7.0
    container_name: ecommerce-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
