-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

ALTER TABLE categories ADD PRIMARY KEY (category_id);
ALTER TABLE categories ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE categories ALTER COLUMN category_name SET NOT NULL;
ALTER TABLE customers ADD UNIQUE (email);
ALTER TABLE customers ADD PRIMARY KEY (customer_id);
ALTER TABLE customers ALTER COLUMN customer_id SET NOT NULL;
ALTER TABLE customers ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE customers ALTER COLUMN last_name SET NOT NULL;
ALTER TABLE customers ALTER COLUMN email SET NOT NULL;
ALTER TABLE orders ADD PRIMARY KEY (order_id);
ALTER TABLE orders ALTER COLUMN order_id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN customer_id SET NOT NULL;
ALTER TABLE order_items ADD PRIMARY KEY (order_item_id);
ALTER TABLE order_items ALTER COLUMN order_item_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN order_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN unit_price SET NOT NULL;
ALTER TABLE products ADD PRIMARY KEY (product_id);
ALTER TABLE products ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE products ALTER COLUMN product_name SET NOT NULL;
ALTER TABLE products ALTER COLUMN price SET NOT NULL;
