-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE TABLE categories (
	category_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	category_name varchar(100) NOT NULL,
	description varchar(500)
) ;


CREATE TABLE customers (
	customer_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	email varchar(100) NOT NULL,
	phone varchar(20),
	address varchar(200),
	created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
) ;


CREATE TABLE orders (
	order_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	customer_id bigint NOT NULL,
	order_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
	total_amount decimal(10,2),
	status varchar(20) DEFAULT 'pending'
) ;


CREATE TABLE order_items (
	order_item_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	order_id bigint NOT NULL,
	product_id bigint NOT NULL,
	quantity bigint NOT NULL,
	unit_price decimal(10,2) NOT NULL
) ;


CREATE TABLE products (
	product_id bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20 ),
	product_name varchar(200) NOT NULL,
	category_id bigint,
	price decimal(10,2) NOT NULL,
	stock_quantity bigint DEFAULT 0,
	description varchar(1000),
	created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
) ;
